#########################################################
# Wordpress on Ubuntu 22.04 LAMP
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  

  pre_tasks:
    - name: Remove existing Drupal directory
      file:
        path: "{{ drupal_composer_install_dir }}"
        state: absent


 
  roles:
    - geerlingguy.php
    - geerlingguy.php-pgsql
    - geerlingguy.postgresql 
    - geerlingguy.nginx
    - geerlingguy.git

    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal
    

